theme: minima
title: My blog
author: Belle de Lune

email: beautifulgoddessdelalune@gmail.com
description: FinDom, at it's finest.

# social links
github_username:  BelleDeLune 

show_excerpts: true # set to false to remove excerpts on the homepage
